// ISSUE-022 — the MemoryStore PORT + in-memory fake reference model (house port+fake pattern, cf. app/rbac,
// app/config-store, app/silo). Every live side effect of the C2 data foundation goes through this port so the
// entity model + tag rules stay unit-testable with NO live DB. The in-memory fake is BOTH the test double AND
// the reference model the live pg adapter (supabase-store.ts) must match 1:1.
//
// Faithful to schema.md §3 Memory (entities / memories) + the 0001 baseline DDL. Invariants enforced in the fake
// EXACTLY as the DB enforces them, so a green offline suite predicts live behaviour:
//   1. entities: exactly one is_internal_org=true row per deployment (0029 partial-unique guard) — a second
//      throws internal_org_exists (mirrors unique_violation).
//   2. entities.type ∈ the configured entity_types list (app-level validation, OD-178; type is plain text).
//   3. memories: cardinality(entity_ids) >= 1 (0001 CHECK / AC-2.MEM.002.2) — a zero-entity write is rejected.
//   4. memories: confidence is null ONLY for source='system_pointer' (0001 CHECK).
//   5. memories: unique(idempotency_key) (ADR-004 §4) — a retried write is a no-op insert (ON CONFLICT DO
//      NOTHING), NOT a duplicate row and NOT an error (returns inserted:false).
//   6. memories: type/source/visibility/sensitivity are the four §Types enums — an out-of-domain value rejected.

import {
  MEMORY_TYPES,
  MEMORY_SOURCES,
  VISIBILITY_TIERS,
  SENSITIVITY_TIERS,
  DEFAULT_ENTITY_TYPES,
  type MemoryType,
  type MemorySource,
  type VisibilityTier,
  type SensitivityTier,
} from './entity-types.ts';
import { computeIdempotencyKey } from './memory.ts';

// ── Row shapes (schema.md §3) ─────────────────────────────────────────────────────────────────────
/** Cross-system identifiers for entity resolution: system slug → external id (e.g. {ghl:"abc", slack:"U123"}). */
export type ExternalRefs = Record<string, string>;

/** entities (schema.md §3 L397-406). maturity / maturity_updated_at exist here but are populated by ISSUE-030. */
export interface EntityRow {
  id: string;
  type: string; // validated vs config_values['entity_types']
  name: string;
  external_refs: ExternalRefs;
  is_internal_org: boolean;
  maturity: number | null; // filled slots / expected slots (ADR-002) — recomputed by ISSUE-030
  maturity_updated_at: string | null;
  created_at: string;
}

/** memories (schema.md §3 L408-430). embedding is a caller input (generated by ISSUE-023's write path); this
 *  slice validates the ROW SHAPE + tags + idempotency the writer (ISSUE-024) populates, not the embedding. */
export interface MemoryRow {
  id: string;
  type: MemoryType;
  content: string;
  embedding: number[]; // vector(1536) not null — opaque here (ISSUE-023 owns vector correctness)
  embedding_model: string;
  entity_ids: string[]; // >=1 (CHECK)
  source: MemorySource;
  source_ref: string | null;
  confidence: number | null; // 0-1; null only for system_pointer
  visibility: VisibilityTier;
  sensitivity: SensitivityTier;
  superseded_by: string | null; // CAS chain; null = live
  content_hash: string;
  idempotency_key: string;
  expires_at: string | null;
  created_at: string;
  updated_at: string;
}

/** The fields a caller supplies to write a memory; id/idempotency_key/timestamps are derived on insert. */
export interface EntityInput {
  type: string;
  name: string;
  external_refs?: ExternalRefs;
  is_internal_org?: boolean;
}

/** Raised by every store/validation failure — carries a machine reason so callers surface, never swallow (#3). */
export class MemoryError extends Error {
  constructor(
    public reason: string,
    message: string,
  ) {
    super(message);
    this.name = 'MemoryError';
  }
}
export const ERR_UNKNOWN_ENTITY_TYPE = 'unknown_entity_type';
export const ERR_INTERNAL_ORG_EXISTS = 'internal_org_exists';
export const ERR_NO_ENTITY = 'no_entity'; // memory with zero entity_ids (AC-2.MEM.002.2)
export const ERR_BAD_MEMORY_TYPE = 'bad_memory_type';
export const ERR_BAD_SOURCE = 'bad_source';
export const ERR_BAD_VISIBILITY = 'bad_visibility';
export const ERR_BAD_SENSITIVITY = 'bad_sensitivity';
export const ERR_CONFIDENCE_RULE = 'confidence_rule'; // confidence null with non-pointer source, or set for pointer
export const ERR_CONFIDENCE_RANGE = 'confidence_range';
export const ERR_NO_CONTENT_HASH = 'no_content_hash';
export const ERR_POINTER_NEEDS_REF = 'pointer_needs_ref'; // system_pointer memory without a source_ref (golden rule)

// ── The port ──────────────────────────────────────────────────────────────────────────────────────
export interface MemoryStore {
  // Entity-type config (config_values['entity_types'] — CFG-entity_types, seeded by 0030).
  listEntityTypes(): Promise<string[]>;

  // Entities.
  listEntities(): Promise<EntityRow[]>;
  getEntity(id: string): Promise<EntityRow | null>;
  internalOrg(): Promise<EntityRow | null>; // the singleton, or null pre-seed
  /** Insert an entity. Validates type ∈ config (unless is_internal_org, whose type is the locked constant) and
   *  enforces the singleton (a 2nd is_internal_org=true throws). Returns the stored row. */
  insertEntity(input: EntityInput): Promise<EntityRow>;

  // Memories.
  /** Idempotent write: dedups on idempotency_key (ON CONFLICT DO NOTHING). Returns {inserted:false} for a
   *  retried write (the key already exists) — never a duplicate row, never an error. Validates the row shape
   *  (>=1 entity, enum domains, confidence rule) BEFORE the insert. */
  insertMemory(row: MemoryRow): Promise<{ inserted: boolean; id: string }>;
  getMemory(id: string): Promise<MemoryRow | null>;
  listMemories(): Promise<MemoryRow[]>;
}

let __seq = 0;
const nextId = () => `id-${++__seq}`;
const nowIso = (n: number) => new Date(n).toISOString();

// ── Row-shape validation shared by the fake AND the live adapter (the MEM invariants, schema.md §3 CHECKs) ──
/** Validates a memory row against the four enum domains + the two DB CHECKs (>=1 entity, confidence rule) +
 *  content_hash presence. Throws MemoryError on the first violation. Pure — called by both stores so offline and
 *  live reject identically. Does NOT validate embedding dimensionality (ISSUE-023). */
export function validateMemoryRow(row: MemoryRow): void {
  if (!MEMORY_TYPES.includes(row.type)) throw new MemoryError(ERR_BAD_MEMORY_TYPE, `memory type '${row.type}' not in ${MEMORY_TYPES.join('/')}`);
  if (!MEMORY_SOURCES.includes(row.source)) throw new MemoryError(ERR_BAD_SOURCE, `source '${row.source}' not a memory_source`);
  if (!VISIBILITY_TIERS.includes(row.visibility)) throw new MemoryError(ERR_BAD_VISIBILITY, `visibility '${row.visibility}' not a visibility_tier`);
  if (!SENSITIVITY_TIERS.includes(row.sensitivity)) throw new MemoryError(ERR_BAD_SENSITIVITY, `sensitivity '${row.sensitivity}' not a sensitivity_tier`);
  if (!Array.isArray(row.entity_ids) || row.entity_ids.length < 1) throw new MemoryError(ERR_NO_ENTITY, 'a memory must reference >=1 entity (AC-2.MEM.002.2)');
  // Confidence rule — mirrors the live 0001 CHECK `(source = 'system_pointer' or confidence is not null)`, which
  // enforces exactly ONE direction: a NON-pointer must carry a confidence. A system_pointer MAY be unscored
  // (confidence null, the writer's convention for pointers) OR carry one — the schema does not forbid it, so the
  // fake must not either (R10: the fake is the DB's reference model, never stricter than its actual CHECKs).
  if (row.source === 'system_pointer') {
    // Golden rule (app-level write-contract, NFR-CMP.002 — not a DB CHECK): a system-of-record pointer MUST
    // reference its source, never copy it, so a system_pointer without a source_ref is malformed. Both the fake
    // and the live adapter apply this via validateMemoryRow, so offline + live reject it identically.
    if (!row.source_ref) throw new MemoryError(ERR_POINTER_NEEDS_REF, 'a system_pointer memory must carry a source_ref (golden rule, NFR-CMP.002)');
    if (row.confidence !== null && (row.confidence < 0 || row.confidence > 1)) throw new MemoryError(ERR_CONFIDENCE_RANGE, `confidence ${row.confidence} out of [0,1]`);
  } else {
    if (row.confidence === null) throw new MemoryError(ERR_CONFIDENCE_RULE, `a ${row.source} memory requires a confidence (0001 CHECK)`);
    if (row.confidence < 0 || row.confidence > 1) throw new MemoryError(ERR_CONFIDENCE_RANGE, `confidence ${row.confidence} out of [0,1]`);
  }
  if (!row.content_hash) throw new MemoryError(ERR_NO_CONTENT_HASH, 'content_hash is required (idempotency component)');
}

// ── The in-memory fake reference model ──────────────────────────────────────────────────────────────
export class InMemoryMemoryStore implements MemoryStore {
  private entityTypes: string[];
  private entities: EntityRow[] = [];
  private memories: MemoryRow[] = [];

  /** Seeds the configured entity-type list to the 0030 default (a fresh deployment). Tests may pass a custom set
   *  to model an operator-customised list (AC-2.ENT.002.2). */
  constructor(entityTypes: readonly string[] = DEFAULT_ENTITY_TYPES) {
    this.entityTypes = [...entityTypes];
  }

  async listEntityTypes(): Promise<string[]> {
    return [...this.entityTypes];
  }
  async listEntities(): Promise<EntityRow[]> {
    return this.entities.map((e) => ({ ...e, external_refs: { ...e.external_refs } }));
  }
  async getEntity(id: string): Promise<EntityRow | null> {
    const e = this.entities.find((x) => x.id === id);
    return e ? { ...e, external_refs: { ...e.external_refs } } : null;
  }
  async internalOrg(): Promise<EntityRow | null> {
    const e = this.entities.find((x) => x.is_internal_org);
    return e ? { ...e, external_refs: { ...e.external_refs } } : null;
  }

  async insertEntity(input: EntityInput): Promise<EntityRow> {
    const isInternal = input.is_internal_org === true;
    // Singleton guard (0029 partial-unique): at most one is_internal_org=true row.
    if (isInternal && this.entities.some((e) => e.is_internal_org)) {
      throw new MemoryError(ERR_INTERNAL_ORG_EXISTS, 'an Internal Org entity already exists (singleton, FR-2.ENT.003)');
    }
    // Type validation (app-level, OD-178). The Internal-Org type is the locked constant and is always valid.
    if (!this.entityTypes.includes(input.type)) {
      throw new MemoryError(ERR_UNKNOWN_ENTITY_TYPE, `entity type '${input.type}' is not in the configured entity_types list`);
    }
    const row: EntityRow = {
      id: nextId(),
      type: input.type,
      name: input.name,
      external_refs: { ...(input.external_refs ?? {}) },
      is_internal_org: isInternal,
      maturity: null,
      maturity_updated_at: null,
      created_at: nowIso(0),
    };
    this.entities.push(row);
    return { ...row, external_refs: { ...row.external_refs } };
  }

  async insertMemory(row: MemoryRow): Promise<{ inserted: boolean; id: string }> {
    validateMemoryRow(row);
    // Idempotent write: a retried step with the same idempotency_key is a no-op (ON CONFLICT DO NOTHING).
    const existing = this.memories.find((m) => m.idempotency_key === row.idempotency_key);
    if (existing) return { inserted: false, id: existing.id };
    const stored: MemoryRow = { ...row, entity_ids: [...row.entity_ids], embedding: [...row.embedding] };
    this.memories.push(stored);
    return { inserted: true, id: stored.id };
  }
  async getMemory(id: string): Promise<MemoryRow | null> {
    const m = this.memories.find((x) => x.id === id);
    return m ? { ...m, entity_ids: [...m.entity_ids], embedding: [...m.embedding] } : null;
  }
  async listMemories(): Promise<MemoryRow[]> {
    return this.memories.map((m) => ({ ...m, entity_ids: [...m.entity_ids], embedding: [...m.embedding] }));
  }

  // ── Test-seam helpers (not part of the port) ──────────────────────────────────────────────────────
  /** Build a well-formed MemoryRow for a test, deriving id/idempotency_key/timestamps. embedding defaults to a
   *  zero vector (ISSUE-023 supplies real embeddings). */
  _memoryRow(partial: Partial<MemoryRow> & Pick<MemoryRow, 'type' | 'content' | 'entity_ids' | 'source' | 'visibility' | 'sensitivity'>): MemoryRow {
    const content_hash = partial.content_hash ?? `h:${partial.content}`;
    const source_ref = partial.source_ref ?? null;
    return {
      id: partial.id ?? nextId(),
      type: partial.type,
      content: partial.content,
      embedding: partial.embedding ?? new Array(1536).fill(0),
      embedding_model: partial.embedding_model ?? 'text-embedding-3-small',
      entity_ids: partial.entity_ids,
      source: partial.source,
      source_ref,
      confidence: partial.confidence ?? (partial.source === 'system_pointer' ? null : 0.8),
      visibility: partial.visibility,
      sensitivity: partial.sensitivity,
      superseded_by: partial.superseded_by ?? null,
      content_hash,
      idempotency_key: partial.idempotency_key ?? computeIdempotencyKey(source_ref, partial.entity_ids, content_hash),
      expires_at: partial.expires_at ?? null,
      created_at: nowIso(0),
      updated_at: nowIso(0),
    };
  }
}
